import Fluent
import Foundation
import SQLKit

struct MigrateCategoryIDToInteger: AsyncMigration {

    func prepare(on database: Database) async throws {
        guard let sqlDB = database as? SQLDatabase else { return }

        // Add auto-increment integer column alongside existing UUID id
        try await sqlDB.raw("ALTER TABLE catalogue_categories ADD COLUMN new_id INTEGER GENERATED BY DEFAULT AS IDENTITY").run()

        // Add temp integer FK column to previews
        try await sqlDB.raw("ALTER TABLE previews ADD COLUMN new_category_id INTEGER").run()

        // Backfill from join
        try await sqlDB.raw("""
            UPDATE previews p
            SET new_category_id = cc.new_id
            FROM catalogue_categories cc
            WHERE p.category_id = cc.id
            """).run()

        // Swap previews FK: drop UUID column, rename integer column
        try await sqlDB.raw("ALTER TABLE previews DROP COLUMN category_id").run()
        try await sqlDB.raw("ALTER TABLE previews RENAME COLUMN new_category_id TO category_id").run()

        // Promote new_id to primary key in catalogue_categories
        try await sqlDB.raw("ALTER TABLE catalogue_categories DROP CONSTRAINT catalogue_categories_pkey").run()
        try await sqlDB.raw("ALTER TABLE catalogue_categories DROP COLUMN id").run()
        try await sqlDB.raw("ALTER TABLE catalogue_categories RENAME COLUMN new_id TO id").run()
        try await sqlDB.raw("ALTER TABLE catalogue_categories ADD PRIMARY KEY (id)").run()

        // Add FK constraint from previews to the new integer primary key
        try await sqlDB.raw("""
            ALTER TABLE previews
            ADD CONSTRAINT previews_category_id_fkey
            FOREIGN KEY (category_id) REFERENCES catalogue_categories(id)
            """).run()
    }

    func revert(on database: Database) async throws {
        guard let sqlDB = database as? SQLDatabase else { return }

        // Add UUID column back to previews
        try await sqlDB.raw("ALTER TABLE previews DROP CONSTRAINT IF EXISTS previews_category_id_fkey").run()
        try await sqlDB.raw("ALTER TABLE previews ADD COLUMN old_category_id UUID").run()

        // Add UUID id back to catalogue_categories
        try await sqlDB.raw("ALTER TABLE catalogue_categories ADD COLUMN old_id UUID DEFAULT gen_random_uuid()").run()

        // Backfill previews from join on integer id
        try await sqlDB.raw("""
            UPDATE previews p
            SET old_category_id = cc.old_id
            FROM catalogue_categories cc
            WHERE p.category_id = cc.id
            """).run()

        // Swap catalogue_categories primary key back to UUID
        try await sqlDB.raw("ALTER TABLE catalogue_categories DROP CONSTRAINT catalogue_categories_pkey").run()
        try await sqlDB.raw("ALTER TABLE catalogue_categories DROP COLUMN id").run()
        try await sqlDB.raw("ALTER TABLE catalogue_categories RENAME COLUMN old_id TO id").run()
        try await sqlDB.raw("ALTER TABLE catalogue_categories ADD PRIMARY KEY (id)").run()

        // Swap previews FK back to UUID
        try await sqlDB.raw("ALTER TABLE previews DROP COLUMN category_id").run()
        try await sqlDB.raw("ALTER TABLE previews RENAME COLUMN old_category_id TO category_id").run()
        try await sqlDB.raw("""
            ALTER TABLE previews
            ADD CONSTRAINT previews_category_id_fkey
            FOREIGN KEY (category_id) REFERENCES catalogue_categories(id)
            """).run()
    }
}
